Numpy Arrays Exercises

1. Een 5x5 identiteitsmatrix met integer waardes.

In [33]:
import numpy as np

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.integers(100, size=(5,5))

array([[16, 83, 70, 50, 71],
       [44, 31, 54, 10, 83],
       [31, 36, 57, 61, 36],
       [ 2,  3, 13, 87, 91],
       [57, 26, 87, 85, 41]], dtype=int64)

2. Een 5x5 matrix met float waardes en overal nul behalve op de 2e nevendiagonaal

In [36]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])